@SuppressWarnings('PMD.ApexCrudViolation')
public without sharing class NLSQDMLServiceWS {
    public static void insertRecord(SObject record) {
        insert record;
    }

    public static void insertRecords(List<SObject> records) {
        insert records;
    }

    public static void updateRecord(SObject record) {
        update record;
    }

    public static void updateRecords(List<SObject> records) {
        update records;
    }
}